name: store
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  age: ^0.0.1
  intl: ^0.16.1
  badges: ^1.1.1
  bubble: ^1.1.9+1
  animations: ^1.1.2
  provider: ^4.3.2+1
  google_fonts: ^1.1.0
  flutter_icons: ^1.1.0
  google_maps_flutter: ^1.0.3
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  firebase_messaging: ^6.0.13
  image_cropper: ^1.3.1
  progress_indicators: ^0.1.5
  shimmer: ^1.1.2
  geolocator:
  giffy_dialog:
  cached_network_image: ^2.3.2+1
  mask_text_input_formatter: ^1.1.0
  url_launcher: ^5.7.5
  firebase_storage:
    git:
      url: git://github.com/danysz/flutterfire.git
      ref: master
      path: packages/firebase_storage
  path: ^1.7.0
  image_picker: ^0.6.6+1
  cupertino_icons: ^0.1.3
  country_pickers: ^1.3.0
  responsive_framework:
  auto_size_text: ^2.1.0
  flutter_progress_hud: ^1.0.2
  smooth_page_indicator: ^0.2.0
  flutter_statusbarcolor: ^0.2.3
  flutter_form_builder: ^3.14.0-alpha.2
  flutter_snake_navigationbar: ^0.4.0+1
  flutter_staggered_animations: ^0.1.2
  sk_onboarding_screen: ^1.0.1
dev_dependencies:
  flutter_launcher_icons: "^0.7.3"
  flutter_native_splash: ^0.1.9
  flutter_test:
    sdk: flutter

flutter_native_splash:
  image: assets/images/splash_screen.png
  color: "42a5f5"
  android: true
  ios: true
  fill: true

flutter_icons:
  image_path: "assets/images/icon.png"
  android: true
  ios: true

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/chat.gif
    - assets/images/logo.png
    - assets/images/icon.png
    - assets/images/logo2.png
    - assets/images/splash_screen.png
    - assets/images/box.png
    - assets/images/marker.png
    - assets/images/onboard1.png
    - assets/images/onboard2.png
    - assets/images/onboard3.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Wavehaus
      fonts:
        - asset: assets/fonts/Wavehaus-Medium.otf
        - asset: assets/fonts/Wavehaus-SemiBold.otf
        - asset: assets/fonts/Wavehaus-Bold.otf
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
